"""Render a property's generated lease (``leases.lease_sections``) as a real,
downloadable PDF — the same 18 sections shown in the in-app Summary tab, so
the two views never disagree. Mirrors ``pdf_gen.py``'s house style (PyMuPDF,
A4, 72/523 margins, lazy ``import fitz``).

Deterministic and fast (~tens of ms), so it's generated on demand per request
rather than cached to disk — every property's lease PDF exists, with nothing
to invalidate.
"""

from __future__ import annotations

import leases

_LEFT, _RIGHT = 72, 523
_TOP = 76
_BREAK_Y = 780
_ACCENT = (0.36, 0.30, 0.86)
_MUTED = (0.45, 0.45, 0.52)
_INK = (0.09, 0.08, 0.14)
_BODY = (0.16, 0.16, 0.22)
_RULE = (0.82, 0.82, 0.90)


def _money(v) -> str:
    try:
        return f"${int(round(float(v))):,}"
    except (TypeError, ValueError):
        return str(v)


def _key_facts_line(kt: dict) -> str:
    parts = [
        f"Rent {_money(kt.get('rent'))}/mo",
        f"Deposit {_money(kt.get('deposit'))}",
        f"Term {kt.get('term_months')} months",
        f"Pets {'Yes' if kt.get('pets') else 'No'}",
        f"Parking {str(kt.get('parking') or 'none').title()}",
        "Furnished" if kt.get("furnished") else "Unfurnished",
    ]
    return "   •   ".join(parts)


def render_lease_pdf(prop: dict, key_terms: dict) -> bytes:
    """The full lease for one property as PDF bytes. ``key_terms`` is the same
    dict the Summary tab's pill row uses (``concierge_api._key_terms``), so
    the PDF header and the in-app summary always show identical numbers."""
    import fitz  # PyMuPDF — lazy import, matches pdf_gen.py

    doc = fitz.open()
    page = doc.new_page()
    max_w = _RIGHT - _LEFT
    y = _TOP

    def new_page():
        nonlocal page, y
        page = doc.new_page()
        y = _TOP

    def wrap(text: str, font: str, size: float) -> list[str]:
        words = (text or "").split()
        lines: list[str] = []
        cur = ""
        for w in words:
            trial = f"{cur} {w}".strip()
            if fitz.get_text_length(trial, fontname=font, fontsize=size) <= max_w:
                cur = trial
            else:
                if cur:
                    lines.append(cur)
                cur = w
        if cur:
            lines.append(cur)
        return lines or [""]

    def text_line(txt: str, size: float, font: str = "helv", color=_INK, gap: float = 6):
        nonlocal y
        if y > _BREAK_Y:
            new_page()
        page.insert_text((_LEFT, y), txt, fontsize=size, fontname=font, color=color)
        y += size + gap

    def paragraph(txt: str, size: float = 10, font: str = "helv", color=_BODY,
                  leading: float | None = None, gap: float = 12):
        nonlocal y
        leading = leading or size * 1.5
        for ln in wrap(txt, font, size):
            if y > _BREAK_Y:
                new_page()
            page.insert_text((_LEFT, y), ln, fontsize=size, fontname=font, color=color)
            y += leading
        y += gap

    def rule(before: float = 2, after: float = 14):
        nonlocal y
        if y > _BREAK_Y:
            new_page()
        y += before
        page.draw_line((_LEFT, y), (_RIGHT, y), color=_RULE, width=0.75)
        y += after

    name = prop.get("name") or "Property"
    pid = prop.get("id", "")
    hood = (prop.get("neighborhood") or {}).get("name") or ""
    city = (prop.get("neighborhood") or {}).get("city") or "Austin"
    place = f"{pid} · {hood + ', ' if hood else ''}{city}, Texas"

    text_line("RESIDENTIAL LEASE AGREEMENT", 9, font="hebo", color=_ACCENT, gap=10)
    text_line(name, 20, font="hebo", color=_INK, gap=6)
    text_line(place, 10, color=_MUTED, gap=14)
    paragraph(_key_facts_line(key_terms), size=10, font="hebo", color=_ACCENT, leading=15, gap=4)
    rule()

    for i, (title, body) in enumerate(leases.lease_sections(prop), start=1):
        text_line(f"{i}. {title}", 12, font="hebo", color=_INK, gap=7)
        paragraph(body, size=10, leading=14.5, gap=14)

    n = len(doc)
    disclaimer = "Synthetic lease generated by RentReady for demonstration — not a legal document."
    for i in range(n):
        pg = doc[i]
        pg.draw_line((_LEFT, 800), (_RIGHT, 800), color=_RULE, width=0.6)
        pg.insert_text((_LEFT, 815), disclaimer, fontsize=7.5, fontname="helv", color=_MUTED)
        label = f"Page {i + 1} of {n}"
        w = fitz.get_text_length(label, fontname="helv", fontsize=7.5)
        pg.insert_text((_RIGHT - w, 815), label, fontsize=7.5, fontname="helv", color=_MUTED)

    data = doc.tobytes(deflate=True)
    doc.close()
    return data
