"""RentReady demo: a single free-tier-eligible EC2 instance.

Deliberately minimal -- no Neo4j server (the app already falls back to an
in-memory property list when Neo4j is unreachable; see backend/graph.py),
no RDS, no load balancer. One t3.micro, one Elastic IP, nginx in front of
uvicorn. Cheap enough to stay inside the AWS free tier for 12 months.
"""

import pathlib

import pulumi
import pulumi_aws as aws
import pulumi_tls as tls

config = pulumi.Config()
instance_type = config.get("instanceType") or "t3.micro"
# Optional address for alarm notifications. AWS's always-free tier covers 10
# CloudWatch alarms and 1,000 SNS email notifications/month, so this costs
# nothing. Left unset, the alarms are still created (and visible in the
# console) but nothing is emailed:
#   pulumi config set alertEmail you@example.com
alert_email = config.get("alertEmail")
# No safe default here on purpose -- an open (0.0.0.0/0) SSH rule is a real
# security risk, so this must be set explicitly:
#   pulumi config set sshCidr <your-public-ip>/32
ssh_cidr = config.require("sshCidr")

user_data = pathlib.Path(__file__).parent.joinpath("user_data.sh").read_text()

# --- SSH key pair -----------------------------------------------------------
# Generated by Pulumi so the private key never has to be typed/copied by
# hand; retrieve it after `pulumi up` with:
#   pulumi stack output privateKeyPem --show-secrets > rentready-key.pem
ssh_key = tls.PrivateKey("rentready-ssh-key", algorithm="RSA", rsa_bits=4096)

key_pair = aws.ec2.KeyPair(
    "rentready-key",
    key_name="rentready-demo",
    public_key=ssh_key.public_key_openssh,
)

# --- Networking (default VPC -- free, already exists in every region) ------
default_vpc = aws.ec2.get_vpc(default=True)

security_group = aws.ec2.SecurityGroup(
    "rentready-sg",
    description="RentReady demo: SSH from one IP, HTTP from anywhere",
    vpc_id=default_vpc.id,
    ingress=[
        aws.ec2.SecurityGroupIngressArgs(
            protocol="tcp", from_port=22, to_port=22, cidr_blocks=[ssh_cidr],
            description="SSH (restricted to your IP)",
        ),
        aws.ec2.SecurityGroupIngressArgs(
            protocol="tcp", from_port=80, to_port=80, cidr_blocks=["0.0.0.0/0"],
            description="HTTP (also serves the ACME HTTP-01 challenge for certbot)",
        ),
        aws.ec2.SecurityGroupIngressArgs(
            protocol="tcp", from_port=443, to_port=443, cidr_blocks=["0.0.0.0/0"],
            description="HTTPS",
        ),
    ],
    egress=[
        aws.ec2.SecurityGroupEgressArgs(
            protocol="-1", from_port=0, to_port=0, cidr_blocks=["0.0.0.0/0"],
        ),
    ],
)

# --- AMI: latest Amazon Linux 2023 (STANDARD, not "minimal") ---------------
# "al2023-ami-*-x86_64" also matches the minimal variant's name
# ("al2023-ami-minimal-2023.12...-x86_64") -- that variant strips out
# ec2-instance-connect, so a lost/misplaced private key becomes unrecoverable
# (no SSM agent here either). Anchoring on "al2023-ami-2023.*" excludes it.
al2023 = aws.ec2.get_ami(
    most_recent=True,
    owners=["amazon"],
    filters=[
        aws.ec2.GetAmiFilterArgs(name="name", values=["al2023-ami-2023.*-x86_64"]),
        aws.ec2.GetAmiFilterArgs(name="virtualization-type", values=["hvm"]),
    ],
)

# --- Instance ----------------------------------------------------------------
instance = aws.ec2.Instance(
    "rentready-demo",
    ami=al2023.id,
    instance_type=instance_type,  # t3.micro -- free-tier eligible
    key_name=key_pair.key_name,
    vpc_security_group_ids=[security_group.id],
    user_data=user_data,
    root_block_device=aws.ec2.InstanceRootBlockDeviceArgs(
        volume_size=30,  # GB -- the AL2023 AMI's snapshot requires >= 30GB;
        # this is exactly the free-tier EBS allowance, not a GB over it.
        volume_type="gp3",
        # Encryption-at-rest with the default AWS-managed key costs NOTHING
        # extra, but it cannot be applied to an existing volume -- turning it on
        # REPLACES the instance. Gated behind a flag so it can't surprise an
        # unrelated `pulumi up`:
        #     pulumi config set --bool encryptRootVolume true
        # Expect ~5 min downtime on the next up, after which re-run
        # infra/deploy.sh and re-issue TLS (`pulumi stack output
        # tlsSetupCommand`) -- the cert lives on the replaced disk.
        encrypted=config.get_bool("encryptRootVolume") or False,
    ),
    tags={"Name": "rentready-demo"},
)

eip = aws.ec2.Eip(
    "rentready-eip",
    instance=instance.id,
    domain="vpc",
    tags={"Name": "rentready-demo"},
)

# --- Monitoring & self-healing (all inside the AWS always-free tier) ---------
# 10 CloudWatch alarms and 1,000 SNS email notifications/month are always free,
# and EC2 alarm recover/reboot actions cost nothing. Uses only the built-in EC2
# metrics -- deliberately NOT the CloudWatch agent, because collecting memory
# and disk requires a daemon whose own footprint matters on a 1GB instance.
alerts = aws.sns.Topic("rentready-alerts", name="rentready-alerts")

if alert_email:
    aws.sns.TopicSubscription(
        "rentready-alerts-email",
        topic=alerts.arn,
        protocol="email",
        endpoint=alert_email,  # AWS emails a one-time confirmation link
    )

_alarm_dims = {"InstanceId": instance.id}

# A FAILED SYSTEM CHECK is AWS-side (host/network); recovery migrates the
# instance to healthy hardware, keeping the instance id, EIP and EBS volume.
aws.cloudwatch.MetricAlarm(
    "rentready-system-check",
    name="rentready-system-check-failed",
    namespace="AWS/EC2",
    metric_name="StatusCheckFailed_System",
    dimensions=_alarm_dims,
    statistic="Maximum",
    comparison_operator="GreaterThanOrEqualToThreshold",
    threshold=1,
    period=60,
    evaluation_periods=2,
    alarm_description="EC2 system status check failed -- auto-recovering the instance.",
    alarm_actions=[
        pulumi.Output.concat("arn:aws:automate:", aws.get_region().name, ":ec2:recover"),
        alerts.arn,
    ],
    treat_missing_data="missing",
)

# A FAILED INSTANCE CHECK is guest-side (kernel panic, exhausted memory,
# unreachable network stack) -- a reboot is the correct remedy. This is the
# alarm that covers the OOM risk on a 1GB box without needing an agent.
aws.cloudwatch.MetricAlarm(
    "rentready-instance-check",
    name="rentready-instance-check-failed",
    namespace="AWS/EC2",
    metric_name="StatusCheckFailed_Instance",
    dimensions=_alarm_dims,
    statistic="Maximum",
    comparison_operator="GreaterThanOrEqualToThreshold",
    threshold=1,
    period=60,
    evaluation_periods=3,
    alarm_description="EC2 instance status check failed -- rebooting.",
    alarm_actions=[
        pulumi.Output.concat("arn:aws:automate:", aws.get_region().name, ":ec2:reboot"),
        alerts.arn,
    ],
    treat_missing_data="missing",
)

# Sustained high CPU on a 1 vCPU burstable instance means credits are draining
# and latency is already degraded. Notify only -- never auto-act on load.
aws.cloudwatch.MetricAlarm(
    "rentready-cpu-high",
    name="rentready-cpu-high",
    namespace="AWS/EC2",
    metric_name="CPUUtilization",
    dimensions=_alarm_dims,
    statistic="Average",
    comparison_operator="GreaterThanThreshold",
    threshold=90,
    period=300,
    evaluation_periods=3,  # ~15 minutes sustained
    alarm_description="CPU above 90% for ~15 minutes on a 1 vCPU instance.",
    alarm_actions=[alerts.arn],
    treat_missing_data="missing",
)

pulumi.export("publicIp", eip.public_ip)
pulumi.export("sshCommand", pulumi.Output.concat(
    "ssh -i rentready-key.pem ec2-user@", eip.public_ip,
))
pulumi.export("privateKeyPem", pulumi.Output.secret(ssh_key.private_key_pem))

# sslip.io resolves "<ip-with-dashes>.sslip.io" straight back to that IP with
# no DNS setup or domain purchase -- a real, publicly resolvable hostname
# certbot's HTTP-01 challenge can issue a trusted cert for. Only known after
# `pulumi up` allocates the EIP, so TLS is a documented post-deploy step
# (same pattern as deploying the app itself) rather than baked into
# user_data.sh, which runs at first boot before the EIP may be attached.
sslip_host = eip.public_ip.apply(lambda ip: ip.replace(".", "-") + ".sslip.io")
pulumi.export("tlsHostname", sslip_host)
pulumi.export("tlsSetupCommand", pulumi.Output.concat(
    "sudo certbot --nginx -d ", sslip_host, " --non-interactive --agree-tos "
    "-m you@example.com --redirect",
))
