"""RentReady demo: a single free-tier-eligible EC2 instance.

Deliberately minimal -- no Neo4j server (the app already falls back to an
in-memory property list when Neo4j is unreachable; see backend/graph.py),
no RDS, no load balancer. One t3.micro, one Elastic IP, nginx in front of
uvicorn. Cheap enough to stay inside the AWS free tier for 12 months.
"""

import pathlib

import pulumi
import pulumi_aws as aws
import pulumi_tls as tls

config = pulumi.Config()
instance_type = config.get("instanceType") or "t3.micro"
# No safe default here on purpose -- an open (0.0.0.0/0) SSH rule is a real
# security risk, so this must be set explicitly:
#   pulumi config set sshCidr <your-public-ip>/32
ssh_cidr = config.require("sshCidr")

user_data = pathlib.Path(__file__).parent.joinpath("user_data.sh").read_text()

# --- SSH key pair -----------------------------------------------------------
# Generated by Pulumi so the private key never has to be typed/copied by
# hand; retrieve it after `pulumi up` with:
#   pulumi stack output privateKeyPem --show-secrets > rentready-key.pem
ssh_key = tls.PrivateKey("rentready-ssh-key", algorithm="RSA", rsa_bits=4096)

key_pair = aws.ec2.KeyPair(
    "rentready-key",
    key_name="rentready-demo",
    public_key=ssh_key.public_key_openssh,
)

# --- Networking (default VPC -- free, already exists in every region) ------
default_vpc = aws.ec2.get_vpc(default=True)

security_group = aws.ec2.SecurityGroup(
    "rentready-sg",
    description="RentReady demo: SSH from one IP, HTTP from anywhere",
    vpc_id=default_vpc.id,
    ingress=[
        aws.ec2.SecurityGroupIngressArgs(
            protocol="tcp", from_port=22, to_port=22, cidr_blocks=[ssh_cidr],
            description="SSH (restricted to your IP)",
        ),
        aws.ec2.SecurityGroupIngressArgs(
            protocol="tcp", from_port=80, to_port=80, cidr_blocks=["0.0.0.0/0"],
            description="HTTP (also serves the ACME HTTP-01 challenge for certbot)",
        ),
        aws.ec2.SecurityGroupIngressArgs(
            protocol="tcp", from_port=443, to_port=443, cidr_blocks=["0.0.0.0/0"],
            description="HTTPS",
        ),
    ],
    egress=[
        aws.ec2.SecurityGroupEgressArgs(
            protocol="-1", from_port=0, to_port=0, cidr_blocks=["0.0.0.0/0"],
        ),
    ],
)

# --- AMI: latest Amazon Linux 2023 (STANDARD, not "minimal") ---------------
# "al2023-ami-*-x86_64" also matches the minimal variant's name
# ("al2023-ami-minimal-2023.12...-x86_64") -- that variant strips out
# ec2-instance-connect, so a lost/misplaced private key becomes unrecoverable
# (no SSM agent here either). Anchoring on "al2023-ami-2023.*" excludes it.
al2023 = aws.ec2.get_ami(
    most_recent=True,
    owners=["amazon"],
    filters=[
        aws.ec2.GetAmiFilterArgs(name="name", values=["al2023-ami-2023.*-x86_64"]),
        aws.ec2.GetAmiFilterArgs(name="virtualization-type", values=["hvm"]),
    ],
)

# --- Instance ----------------------------------------------------------------
instance = aws.ec2.Instance(
    "rentready-demo",
    ami=al2023.id,
    instance_type=instance_type,  # t3.micro -- free-tier eligible
    key_name=key_pair.key_name,
    vpc_security_group_ids=[security_group.id],
    user_data=user_data,
    root_block_device=aws.ec2.InstanceRootBlockDeviceArgs(
        volume_size=30,  # GB -- the AL2023 AMI's snapshot requires >= 30GB;
        # this is exactly the free-tier EBS allowance, not a GB over it.
        volume_type="gp3",
    ),
    tags={"Name": "rentready-demo"},
)

eip = aws.ec2.Eip(
    "rentready-eip",
    instance=instance.id,
    domain="vpc",
    tags={"Name": "rentready-demo"},
)

pulumi.export("publicIp", eip.public_ip)
pulumi.export("sshCommand", pulumi.Output.concat(
    "ssh -i rentready-key.pem ec2-user@", eip.public_ip,
))
pulumi.export("privateKeyPem", pulumi.Output.secret(ssh_key.private_key_pem))

# sslip.io resolves "<ip-with-dashes>.sslip.io" straight back to that IP with
# no DNS setup or domain purchase -- a real, publicly resolvable hostname
# certbot's HTTP-01 challenge can issue a trusted cert for. Only known after
# `pulumi up` allocates the EIP, so TLS is a documented post-deploy step
# (same pattern as deploying the app itself) rather than baked into
# user_data.sh, which runs at first boot before the EIP may be attached.
sslip_host = eip.public_ip.apply(lambda ip: ip.replace(".", "-") + ".sslip.io")
pulumi.export("tlsHostname", sslip_host)
pulumi.export("tlsSetupCommand", pulumi.Output.concat(
    "sudo certbot --nginx -d ", sslip_host, " --non-interactive --agree-tos "
    "-m you@example.com --redirect",
))
